"""Generates the Python script that Kaggle runs as the notebook body.

It is a *script* kernel, not an .ipynb: the remote side only has to boot a
tunnel and block, so there is nothing a notebook buys us over plain source.
Config is injected as a JSON literal because Kaggle has no API for Secrets --
the notebook is private and group-shared, so the blast radius is the group.
"""

from __future__ import annotations

import ast
import json
import re
from pathlib import Path

MARKER = "# Generated by kdev"
READY_MARKER = "KDEV_READY"
STAGE_MARKER = "KDEV_STAGE"

#: Ordered stages the remote script announces, for the local progress display.
STAGES = [
    ("sshd", "Installing SSH server"),
    ("env", "Exporting notebook environment"),
    ("repo", "Syncing workspace"),
    ("tunnel", "Starting Cloudflare tunnel"),
]

_TEMPLATE = r'''# Generated by kdev -- do not edit here, edit your kdev config and re-run.
import json, os, pathlib, shutil, signal, subprocess, sys, time

CFG = json.loads(r"""__CONFIG_JSON__""")
READY = "__READY_MARKER__"
STAGE = "__STAGE_MARKER__"


def stage(name):
    print(f"{STAGE} {name}", flush=True)


def sh(cmd, check=True, **kw):
    print(f"$ {cmd}", flush=True)
    return subprocess.run(cmd, shell=True, check=check, **kw)


def install_box():
    """Put kdev's on-box module in place and import it.

    It arrives inside CFG so the box has it from the first second, without
    waiting on a laptop that may already have gone to sleep.
    """
    run = pathlib.Path("/root/.kdev")
    run.mkdir(parents=True, exist_ok=True)
    (run / "kdev_box.py").write_text(CFG["box_script"])
    launcher = run / "run"
    launcher.write_text(f"#!/bin/sh\nexec {sys.executable} /root/.kdev/kdev_box.py \"$@\"\n")
    launcher.chmod(0o755)
    sys.path.insert(0, str(run))
    import kdev_box
    return kdev_box


def session_id():
    """Kaggle puts the session id in the container name; kdev needs it to
    cancel a box it can no longer reach over ssh."""
    name = os.environ.get("KAGGLE_CONTAINER_NAME", "")
    parts = name.rsplit("-", 2)
    return parts[1] if len(parts) == 3 and parts[1].isdigit() else ""


def install_sshd(box):
    if not shutil.which("sshd"):
        # check=False: a transient apt mirror failure must not end the session
        # before we have even said why. The explicit check below is the real one.
        sh("apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y openssh-server",
           check=False)
    if not (shutil.which("sshd") or pathlib.Path("/usr/sbin/sshd").exists()):
        raise SystemExit("could not install openssh-server; see the apt output above")
    pathlib.Path("/var/run/sshd").mkdir(parents=True, exist_ok=True)

    # The key of the machine that started this session, plus every key saved
    # in the workspace -- so any machine that has ever used it can get in.
    box.install_keys(CFG["ssh_public_key"])

    # Password auth stays off: the only way in is the key you already hold.
    pathlib.Path("/etc/ssh/sshd_config.d/kdev.conf").parent.mkdir(parents=True, exist_ok=True)
    pathlib.Path("/etc/ssh/sshd_config.d/kdev.conf").write_text(
        "PermitRootLogin prohibit-password\n"
        "PermitUserEnvironment yes\n"
        "PasswordAuthentication no\n"
        "PubkeyAuthentication yes\n"
        "ClientAliveInterval 30\n"
        "ClientAliveCountMax 240\n"
        "AcceptEnv *\n"
    )
    sh("ssh-keygen -A")
    sh("service ssh restart || /usr/sbin/sshd")


def export_env():
    """Give every ssh session the notebook's environment -- not only terminals.

    sshd starts sessions with a bare environment: no conda, no CUDA, no Kaggle
    variables. A hook in .bashrc only helps interactive shells (Ubuntu's .bashrc
    returns early otherwise), so `ssh kaggle python train.py`, VS Code's server
    and its extensions all got a PATH without the GPU tools -- measured:
    `nvidia-smi: command not found` on a T4 box. ~/.ssh/environment is read by
    sshd itself for every session (PermitUserEnvironment is on in kdev.conf).
    """
    skip = {"LS_COLORS", "_", "PWD", "OLDPWD", "SHLVL", "TERM",
            "SSH_CLIENT", "SSH_CONNECTION", "SSH_TTY"}
    env = {k: v for k, v in sorted(os.environ.items()) if k not in skip and "\n" not in v}
    ssh_env = pathlib.Path("/root/.ssh/environment")
    ssh_env.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    ssh_env.write_text("".join(f"{k}={v}\n" for k, v in env.items()))
    ssh_env.chmod(0o600)

    # Also kept as a sourceable file, for scripts that start from a clean env.
    pathlib.Path("/root/.kdev_env.sh").write_text(
        "".join(f"export {k}={json.dumps(v)}\n" for k, v in env.items()))
    bashrc = pathlib.Path("/root/.bashrc")
    hook = "\n[ -f /root/.kdev_env.sh ] && . /root/.kdev_env.sh\ncd /kaggle/working\n"
    if "kdev_env" not in (bashrc.read_text() if bashrc.exists() else ""):
        with bashrc.open("a") as f:
            f.write(hook)


def add_env(name, value):
    """Add one variable to every future ssh session."""
    os.environ[name] = value
    with pathlib.Path("/root/.ssh/environment").open("a") as f:
        f.write(f"{name}={value}\n")
    with pathlib.Path("/root/.kdev_env.sh").open("a") as f:
        f.write(f"export {name}={json.dumps(value)}\n")


def install_cloudflared():
    if shutil.which("cloudflared"):
        return "cloudflared"
    url = ("https://github.com/cloudflare/cloudflared/releases/latest/download/"
           "cloudflared-linux-amd64")
    sh(f"curl -fsSL {url} -o /usr/local/bin/cloudflared && chmod +x /usr/local/bin/cloudflared")
    return "/usr/local/bin/cloudflared"


def start_tunnel(binary):
    pathlib.Path("/kaggle/working").mkdir(parents=True, exist_ok=True)
    log = open("/kaggle/working/cloudflared.log", "w")
    host = CFG.get("tunnel_hostname") or None

    if CFG.get("tunnel_credentials"):
        # Locally-managed: ingress comes from the config we write right here, so
        # nothing has to be provisioned in the Zero Trust dashboard.
        cf_dir = pathlib.Path("/root/.cloudflared")
        cf_dir.mkdir(parents=True, exist_ok=True)
        creds = cf_dir / "creds.json"
        creds.write_text(CFG["tunnel_credentials"])
        creds.chmod(0o600)
        conf = cf_dir / "config.yml"
        conf.write_text(
            f"tunnel: {CFG['tunnel_id']}\n"
            f"credentials-file: {creds}\n"
            "ingress:\n"
            f"  - hostname: {host}\n"
            "    service: ssh://localhost:22\n"
            "  - service: http_status:404\n"
        )
        cmd = [binary, "--no-autoupdate", "--config", str(conf),
               "tunnel", "run", CFG["tunnel_id"]]
    elif CFG.get("tunnel_token"):
        # Remotely-managed: ingress must already exist in the dashboard, because
        # --token makes cloudflared ignore any local config.
        cmd = [binary, "--no-autoupdate", "tunnel", "run", "--token", CFG["tunnel_token"]]
    else:
        cmd = [binary, "--no-autoupdate", "tunnel", "--url", "ssh://localhost:22"]
        host = None

    proc = subprocess.Popen(cmd, stdout=log, stderr=subprocess.STDOUT)
    if host is None:
        host = wait_for_quick_tunnel_host("/kaggle/working/cloudflared.log")
    return proc, host


def wait_for_quick_tunnel_host(path, timeout=120):
    """Quick tunnels only announce their random hostname in their own log."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        text = pathlib.Path(path).read_text() if pathlib.Path(path).exists() else ""
        for token in text.split():
            if token.startswith("https://") and token.endswith(".trycloudflare.com"):
                return token.removeprefix("https://")
        time.sleep(2)
    raise SystemExit("cloudflared never announced a hostname; see cloudflared.log")


def clone_repo():
    remote = CFG.get("git_remote")
    if not remote:
        return None
    if CFG.get("git_deploy_key"):
        key = pathlib.Path("/root/.ssh/git_deploy")
        key.write_text(CFG["git_deploy_key"].rstrip() + "\n")
        key.chmod(0o600)
        add_env("GIT_SSH_COMMAND",
                f"ssh -i {key} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new")

    dest = pathlib.Path("/kaggle/working") / remote.rstrip("/").split("/")[-1].removesuffix(".git")
    if dest.exists():
        sh(f"git -C {dest} pull --ff-only", check=False)
    else:
        sh(f"git clone {remote} {dest}", check=False)
    return dest


def snapshot(dest):
    """Best-effort commit+push so a timeout does not eat the session's work."""
    if not dest or not dest.exists():
        return
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    sh(f"git -C {dest} add -A", check=False)
    sh(f'git -C {dest} -c user.email=kdev@local -c user.name=kdev '
       f'commit -m "kdev autosave {stamp}"', check=False)
    sh(f"git -C {dest} push", check=False)


def end_run():
    """Make sure nothing below this cell runs once the session is over.

    Returning normally would let Save & Run All carry on into whatever sits
    under this cell -- after `kdev down`, on your quota, rewriting files that
    were just saved (measured on a real notebook).
    """
    try:
        ip = get_ipython()  # only defined inside a notebook kernel
    except NameError:
        ip = None
    if ip is not None:
        # A notebook: blank every cell after this one. papermill still walks
        # them, finds nothing to run, and the version ends COMPLETE -- where
        # killing the kernel would mark it ERROR.
        ip.input_transformers_cleanup.append(lambda lines: [])
        return
    # A script: nothing after this line may run. Measured to end COMPLETE, with
    # /kaggle/working saved.
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(0)


CHECKPOINT_SECONDS = 900
META_SECONDS = 30


def main():
    box = install_box()
    sid = session_id()
    # Who started it matters: Kaggle lets only that account cancel it.
    print(f"KDEV_SESSION id={sid} by={CFG.get('run_by', '')}", flush=True)
    # Before anything slow: record which saved versions this session is meant
    # to be built on, so even a session killed during apt-get tells the next
    # one what it was supposed to contain.
    box.init_state(CFG.get("restore_layers") or [], sid, CFG.get("run_by", ""),
                   CFG.get("notebook", ""))

    stage("sshd"); install_sshd(box)
    stage("env"); export_env()
    stage("repo"); repo = clone_repo()
    stage("tunnel"); proc, host = start_tunnel(install_cloudflared())

    # The CLI greps stdout for this line to know the box is reachable.
    print(f"{READY} host={host} user=root", flush=True)
    print(f"{READY} ssh -o ProxyCommand='cloudflared access ssh --hostname {host}' root@{host}",
          flush=True)

    deadline = time.time() + CFG["hold_seconds"]
    # So a machine that connects later can say when this box really ends,
    # rather than guess from its own defaults.
    box.update_state(ends=int(deadline))
    stop = {"now": False}
    signal.signal(signal.SIGTERM, lambda *_: stop.__setitem__("now", True))
    next_checkpoint = time.time() + CHECKPOINT_SECONDS
    next_meta = time.time() + META_SECONDS
    try:
        stop_file = pathlib.Path("/kaggle/working/.kdev-stop")
        while time.time() < deadline and not stop["now"]:
            if stop_file.exists():
                print("KDEV_STOP requested", flush=True)
                stop_file.unlink(missing_ok=True)
                break
            if proc.poll() is not None:
                print("cloudflared exited; see cloudflared.log", flush=True)
                break
            # Kaggle commits /kaggle/working only when the run ends, and there
            # is no API to commit mid-run. If the box is lost to an infra fault
            # at hour 7 of 9, the teardown push never happens -- so push on a
            # timer too, when there is a remote to push to.
            if repo and time.time() >= next_checkpoint:
                print("KDEV_CHECKPOINT", flush=True)
                snapshot(repo)
                next_checkpoint = time.time() + CHECKPOINT_SECONDS
            # Kaggle's snapshot keeps file contents but drops symlinks, empty
            # dirs and exec bits. Note them often: a kill costs at most one
            # interval of metadata, never the files.
            if time.time() >= next_meta:
                try:
                    box.record_meta()
                except Exception as e:  # a bad scan must never end the session
                    print(f"KDEV_META failed: {e}", flush=True)
                next_meta = time.time() + META_SECONDS
            # A heartbeat keeps the log stream flowing so the CLI can tell the
            # difference between 'alive and idle' and 'dead'.
            left = int(deadline - time.time())
            print(f"KDEV_ALIVE seconds_left={left}", flush=True)
            # Short sleeps so a stop request is noticed promptly.
            for _ in range(6):
                if stop_file.exists() or stop["now"]:
                    break
                time.sleep(5)
    finally:
        try:
            box.record_meta()
        except Exception as e:
            print(f"KDEV_META failed: {e}", flush=True)
        snapshot(repo)
        proc.terminate()
        print("KDEV_DONE", flush=True)
        end_run()


main()
'''


def render(
    *,
    ssh_public_key: str,
    tunnel_hostname: str,
    hold_seconds: int,
    run_by: str = "",
    tunnel_token: str = "",
    tunnel_credentials: str = "",
    tunnel_id: str = "",
    git_remote: str = "",
    git_deploy_key: str = "",
    restore_layers: list[str] | None = None,
    notebook: str = "",
) -> str:
    if tunnel_credentials and not (tunnel_id and tunnel_hostname):
        raise ValueError("tunnel credentials need both tunnel_id and tunnel_hostname")
    cfg = {
        "ssh_public_key": ssh_public_key,
        "tunnel_token": tunnel_token,
        "tunnel_credentials": tunnel_credentials,
        "tunnel_id": tunnel_id,
        "tunnel_hostname": tunnel_hostname,
        "hold_seconds": hold_seconds,
        "run_by": run_by,
        "git_remote": git_remote,
        "git_deploy_key": git_deploy_key,
        "restore_layers": list(restore_layers or []),
        "notebook": notebook,
        "box_script": BOX_SCRIPT.read_text(),
    }
    # json.dumps escapes every quote and backslash, so the blob can never close
    # the r"""...""" literal it lands in. Parsing the result proves it rather
    # than assuming it -- a broken render fails here, not 3 minutes into a
    # Kaggle session.
    blob = json.dumps(cfg)
    src = (
        _TEMPLATE.replace("__CONFIG_JSON__", blob)
        .replace("__READY_MARKER__", READY_MARKER)
        .replace("__STAGE_MARKER__", STAGE_MARKER)
    )
    try:
        ast.parse(src)
    except SyntaxError as e:
        raise ValueError(f"config broke the generated script: {e}") from e
    return src


BOX_SCRIPT = Path(__file__).with_name("kdev_box.py")

#: Settings a second machine can take from the notebook itself, so joining an
#: existing workspace does not mean setting the tunnel up all over again. The
#: SSH key is deliberately absent: every machine brings its own.
SHARED_SETTINGS = (
    "tunnel_hostname",
    "tunnel_id",
    "tunnel_credentials",
    "tunnel_token",
    "git_remote",
    "git_deploy_key",
)

_CFG_RE = re.compile(r'CFG = json\.loads\(r"""(.*?)"""\)', re.DOTALL)


def _source_text(source: str) -> str:
    """The code in a notebook or script, as one string."""
    stripped = (source or "").strip()
    if stripped.startswith("{"):
        try:
            nb = json.loads(stripped)
        except json.JSONDecodeError:
            return source or ""
        if isinstance(nb, dict) and isinstance(nb.get("cells"), list):
            return "\n".join(
                "".join(c.get("source") or "")
                if isinstance(c.get("source"), list)
                else str(c.get("source") or "")
                for c in nb["cells"]
            )
    return source or ""


def extract_config(source: str) -> dict:
    """The kdev config baked into a notebook's source, or {} if there is none."""
    m = _CFG_RE.search(_source_text(source))
    if not m:
        return {}
    try:
        cfg = json.loads(m.group(1))
    except json.JSONDecodeError:
        return {}
    return {k: cfg[k] for k in SHARED_SETTINGS if cfg.get(k)} if isinstance(cfg, dict) else {}


CELL_HEADER = f"{MARKER} -- this cell is the session: it ends the run when it stops, so nothing below it ever executes."
SCRIPT_BEGIN = f"{MARKER} >>>"
SCRIPT_END = f"{MARKER} <<<"


#: What Kaggle's papermill runner needs to start a notebook at all. Without a
#: kernelspec it fails before the first cell: "No kernel name found in
#: notebook" (measured).
KERNELSPEC = {"name": "python3", "display_name": "Python 3", "language": "python"}


def _runnable(nb: dict) -> dict:
    meta = nb.setdefault("metadata", {})
    if not (meta.get("kernelspec") or {}).get("name"):
        meta["kernelspec"] = dict(KERNELSPEC)
    meta.setdefault("language_info", {"name": "python"})
    nb.setdefault("nbformat", 4)
    nb.setdefault("nbformat_minor", 4)
    return nb


def _is_kdev_cell(cell: dict) -> bool:
    src = cell.get("source") or ""
    text = "".join(src) if isinstance(src, list) else str(src)
    return MARKER in text.split("\n", 3)[0] if text else False


def inject(existing: str, script: str) -> tuple[str, str]:
    """Put the bootstrap in front of a notebook without destroying it.

    Save & Run All executes top to bottom, and the injected cell blocks for the
    whole session, so the user's own cells never run -- but they are still
    there, and still theirs. Re-running replaces kdev's cell rather than
    stacking another one on top.

    Returns (source, kernel_type).
    """
    stripped = (existing or "").strip()

    if stripped.startswith("{"):
        try:
            nb = json.loads(stripped)
        except json.JSONDecodeError:
            nb = None
        if isinstance(nb, dict) and isinstance(nb.get("cells"), list):
            cells = [c for c in nb["cells"] if not _is_kdev_cell(c)]
            nb["cells"] = [
                {
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {},
                    "outputs": [],
                    "source": (CELL_HEADER + "\n" + script).splitlines(keepends=True),
                },
                *cells,
            ]
            return json.dumps(_runnable(nb)), "notebook"

    if stripped:
        # A plain script: keep the user's code below a delimited kdev block.
        body = stripped
        if SCRIPT_BEGIN in body and SCRIPT_END in body:
            head, _, rest = body.partition(SCRIPT_BEGIN)
            _, _, tail = rest.partition(SCRIPT_END)
            body = (head + tail).strip()
        block = f"{SCRIPT_BEGIN}\n{script}\n{SCRIPT_END}"
        return (block + ("\n\n" + body if body else "") + "\n"), "script"

    # Nothing there yet: a one-cell notebook, so cells can be added underneath.
    return json.dumps(
        _runnable(
            {
                "cells": [
                    {
                        "cell_type": "code",
                        "execution_count": None,
                        "metadata": {},
                        "outputs": [],
                        "source": (CELL_HEADER + "\n" + script).splitlines(keepends=True),
                    }
                ],
            }
        )
    ), "notebook"
